---
name: Lab-Tools
version: 1.2
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
abstract: Tools to obtain and work with data in the laboratory
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  File::Basename: 0
  File::Copy: 0
  Time::HiRes: 0
  XML::DOM: 0
  XML::Generator: 0
  encoding::warnings: 0
provides:
  Lab::Data::Meta:
    file: lib/Lab/Data/Meta.pm
    version: 1.0000
  Lab::Data::Plotter:
    file: lib/Lab/Data/Plotter.pm
    version: 1.0000
  Lab::Data::Writer:
    file: lib/Lab/Data/Writer.pm
    version: 0.0000
  Lab::Data::XMLtree:
    file: lib/Lab/Data/XMLtree.pm
    version: 1.0000
  Lab::Measurement:
    file: lib/Lab/Measurement.pm
    version: 0.0000
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
