---
abstract: 'Tools to obtain and handle data with Lab::VISA'
author:
  - 'Daniel Schröer <schroeer@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lab-Tools
provides:
  Lab::Data::Meta:
    file: lib/Lab/Data/Meta.pm
    version: 1.41
  Lab::Data::Plotter:
    file: lib/Lab/Data/Plotter.pm
    version: 1.41
  Lab::Data::Writer:
    file: lib/Lab/Data/Writer.pm
    version: 1.41
  Lab::Data::XMLtree:
    file: lib/Lab/Data/XMLtree.pm
    version: 1.41
  Lab::Measurement:
    file: lib/Lab/Measurement.pm
    version: 1.41
recommends:
  Lab::Instrument: 2.00
  Lab::VISA: 2.03
requires:
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  File::Basename: 0
  File::Copy: 0
  Time::HiRes: 0
  XML::DOM: 0
  XML::Generator: 0
  XML::Twig: 0
  encoding::warnings: 0
resources:
  MailingList: https://www-mailman.uni-regensburg.de/mailman/listinfo/lab-visa-users
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Lab-Tools
  homepage: http://labvisa.de
  license: http://dev.perl.org/licenses/
version: 1.41
